[package]
name = "pretty-logging"
edition = "2024"
version = "0.1.0"

[dependencies]
colored = "3.0.0"
log = "0.4.27"
time = { version = "0.3.42", features = ["formatting", "local-offset", "macros"] }
